CREATE TABLE geocoder_api_log_with_parameters (
geocoder_api_log_sysid INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
log_datetime TIMESTAMPTZ NOT NULL, 
ip_address VARCHAR, api_key VARCHAR, 
method VARCHAR, protocol VARCHAR, 
status_code SMALLINT, 
resource VARCHAR, 
format VARCHAR, 
log_entry VARCHAR, 
addressstring BOOLEAN, 
autocomplete BOOLEAN, 
bbox BOOLEAN, 
brief BOOLEAN, 
centre BOOLEAN, 
civicnumber BOOLEAN, 
civicnumbersuffix BOOLEAN, 
echo BOOLEAN, 
excludeunits BOOLEAN, 
extrapolate BOOLEAN, 
interpolation BOOLEAN, 
localities BOOLEAN, 
localityname BOOLEAN, 
locationdescriptor BOOLEAN, 
matchprecision BOOLEAN, 
matchprecisionnot BOOLEAN, 
maxdistance BOOLEAN, 
maxresults BOOLEAN, 
maxdegree BOOLEAN, 
mindegree BOOLEAN, 
minscore BOOLEAN, 
notlocalities BOOLEAN, 
onlycivic BOOLEAN, 
outputsrs BOOLEAN, 
parcelpoint BOOLEAN, 
point BOOLEAN, 
provincecode BOOLEAN, 
setback BOOLEAN, 
sitename BOOLEAN, 
streetdirection BOOLEAN, 
streetname BOOLEAN, 
streetqualifier BOOLEAN, 
streettype BOOLEAN, 
tags BOOLEAN, 
unitdesignator BOOLEAN, 
unitnumber BOOLEAN, 
unitnumbersuffix BOOLEAN
);

CREATE INDEX geocoder_api_log_with_parameters_log_datetime_idx ON geocoder_api_log_with_parameters(log_datetime);
CREATE INDEX geocoder_api_log_with_parameters_api_key_idx ON geocoder_api_log_with_parameters(api_key);
CREATE INDEX geocoder_api_log_with_parameters_resource_idx ON geocoder_api_log_with_parameters(resource);
